stages:
  - build
  - test

build:
  stage: build
  tags: 
    - docker
  image: maven:3.8.1-jdk-11
  artifacts:
    paths:
      - target/*
  script:
    - mvn compile

test:
  stage: test
  tags:
    - docker
  image: maven:3.8.1-jdk-11
  script:
    - mvn test